### PR TITLE
Avoid pulling in all Tokio features

### PR DESCRIPTION
**Pull request by Alexis211**

### CODE REVIEW

**Comment by Alexis211** [comment]
It would be nice if the crate was updated on crates.io to include this and my previous patch. Thanks :)

**Review by Dhole — APPROVED** [review]

**Comment by Dhole** [comment]
Thanks for the PR!
I see that you made two commits where the first one fails the tests and the second one fixes it.
Could you squash the two commits into one please?

**Comment by Alexis211** [comment]
Sorry for that. Here's a squashed version.

**Comment by Dhole** [comment]
@Alexis211 we just published version 0.1.2 to crates.io!  This release includes your two previous PRs

**Comment by Alexis211** [comment]
Thank you!

**Pull request merged**
